name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
  
    - name: Install modules
      run: yarn --prefer-offline
      
#     - name: test
#       run: yarn test
    - name: build
      run: CI=false yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 200m
          script: |
            docker build https://github.com/group27-endgame/advella-frontend-webapp.git#main -t advella-webapp
            
            docker rm -f advella-webapp
            
            docker run -d \
            --name=advella-webapp \
            --network=advella \
            -p 3001:80 \
            --restart unless-stopped \
            advella-webapp
